version: 2
jobs:
    build:

        working_directory: ~/oauth2-authorization-proxy-server-spring-boot

        docker:
            - image: openjdk:17-jdk-oracle

        steps:

            - checkout

            - run:
                name: Clean
                command: ./gradlew clean

            - run:
                name: Compile
                command: ./gradlew compileJava compileTestJava assemble

            - run:
                name: Test
                command: ./gradlew test

            - run:
                name: Test coverage
                command: ./gradlew jacocoTestReport

            - run:
                name: Javadoc
                command: ./gradlew javadoc

            - run:
                name: Javadoc aggregation
                command: ./gradlew aggregateJavadocs

            - run:
                name: Collect artifacts
                command: ./.circleci/collect-artifacts.sh
                when: always

            - store_artifacts:
                path: ~/oauth2-authorization-proxy-server-spring-boot/build/libs
